[package]
name = "wabper-common"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.3.2"
axum = "0.4.4"
diesel = { version = "2.2.3", features = ["postgres", "r2d2"] }
diesel_migrations = "1.4.0"
hyper = "0.14.16"
r2d2 = "0.8.9"
rand = "0.8.4"
