[package]
edition = "2021"
name = "wabper-db"
version = "0.1.0"

[dependencies]
serde = "1.0.136"
tracing = "0.1.29"
diesel_migrations = "1.4.0"

[dependencies.diesel]
features = ["postgres", "r2d2"]
version = "1.4.4"

[dependencies.wabper-common]
path = "../common"
